### ISSUE TITLE
didn't work with .NET8

### ISSUE THREAD

**Issue by digiBee-GmbH** [1-max-1/WASMSerialTerminal#15]
Hi, 
We migrated our WebAssembly to NetCore 8.
It does not work,. We get an error 
Error: One or more errors occurred. (An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.)
    at Jn (marshal-to-js.ts:349:18)
    at xl (marshal-to-js.ts:306:28)
    at 00b217ca:0x1fa8f
    at 00b217ca:0x1bf5a
    at 00b217ca:0xf141
    at 00b217ca:0x1e7a9
    at 00b217ca:0x1ef9f
    at 00b217ca:0xcfbb
    at 00b217ca:0x4412f
    at e.<computed> (cwraps.ts:338:24)

We switched your Assembly to NetCore 8 and updated the packages.
It does not crash but stays in a loop.

How can we fix this?

Kind regards,

Frank

**Comment by 1-max-1** [comment]
I can't reproduce this
